### ISSUE TITLE
kebab filter seems to be missing (from nunjucks?)

### ISSUE THREAD

**Issue by der-bingle** [jhotmann/node-rename-cli#146]
**Describe the bug**
The `kebab` filter seems to be missing

**To Reproduce:**
1. `Random File.pdf`
2. `rename *.pdf  "{{ f | kebab }}"`
3. **Error:** 
```
/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/src/lib.js:36
    err = new Error(old.message);
          ^
Template render error: (unknown path)
  Error: filter not found: kebab
    at Object._prettifyError (/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:17:3)
    at Template.render (/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/src/environment.js:380:17)
    at Object.renderString (/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/node_modules/nunjucks/index.js:99:14)
    at Operation.replaceVariables (/Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/src/operation.js:40:34)
    at async /Users/luke/.local/share/nvm/v17.4.0/lib/node_modules/rename-cli/src/batch.js:29:68
```

**Expected behavior**
For file to be renamed `random-file.pdf`

**Desktop:**
 - OS: macOS 12.2
 - iTerm2/fish
 - Rename Version 7.0.2

---

Been seeing this one for a while, finally getting around to opening an issue. Obviously the workaround is just to do `"{{ f | replace(' ', '-') | lower }}"`, but I thought you'd want to know. 

Just checked the rest of the built in filters, same error with `snake` as well.

**Comment by ajboni** [comment]
`snake` has the same issue
